version: "3.9"
services:
  database:
    image: postgres
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      ENV: ${ENV}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - ovl_net
  app:
    container_name:  ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        APP_DIR: ${APP_DIR}
        APP_USER: ${APP_USER}
    environment:
      ENV: ${ENV}
      RAILS_ENV: ${RAILS_ENV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TERM: xterm-256color
    volumes:
      - .:${APP_DIR}
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - ovl_net

networks:
  ovl_net:
    external:
      name: msbridge
